plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.syyun.meetinginterpreter'
    compileSdk 35

    defaultConfig {
        applicationId 'com.syyun.meetinginterpreter'
        minSdk 31
        targetSdk 35
        versionCode 3
        versionName '1.1.1'
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
}

dependencies {
    implementation 'com.google.mlkit:translate:17.0.3'
}
